version: '3'
services:

  urlCoder:
    container_name: urlCoder
    image: golang:1.21.4
  
    depends_on:
       - postgres       
    environment:
      ENVIRONMENT: development
    volumes:
      - ./:/app/
    working_dir: /app
    expose:
      - 8180
    ports:
      - '8180:8180'
    command: >
     bash -c "go run ./cmd/main.go"

  postgres:
    container_name: postgres
    image: postgres:latest

    environment:
     POSTGRES_DB: url
     POSTGRES_USER:  user
     POSTGRES_PASSWORD: user
    ports:
      - '5432:5432'
    volumes:
      - ./../db:/var/lib/postgresql


# docker run --name buy-pg-latest -p 5432:5432 -e POSTGRES_USER=buyadmin -e POSTGRES_PASSWORD=buy -e POSTGRES_DB=buydb -v D:/code/buyList/docker/pg-data:/var/lib/pg -d postgres:latest